# RPI3, SDL2, 32-bit
steps:
  - checkout: self
    submodules: true
    clean: true
    
  - script: VERSION_TAG=`git describe --abbrev=0` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
    displayName: Set the tag name as an environment variable

  - script: |
      cd external/capsimg
      ./bootstrap.fs
      ./configure.fs
      make -f Makefile.fs
      cp capsimg.so $(Build.SourcesDirectory)
      cd $(Build.SourcesDirectory)
      make -j4 PLATFORM=rpi3-sdl2
      mkdir amiberry-rpi3-sdl2-32bit
    displayName: 'Compile for RPI3 (SDL2) 32-bit'
  
  - task: CopyFiles@2
    inputs:
     Contents: |
        amiberry
        capsimg.so
        abr/**
        conf/**
        controllers/**
        data/**
        kickstarts/**
        savestates/**
        screenshots/**
        whdboot/**
     TargetFolder: amiberry-rpi3-sdl2-32bit

  - task: ArchiveFiles@2
    displayName: 'Archive rpi3_sdl2_release'
    inputs:
      rootFolderOrFile: 'amiberry-rpi3-sdl2-32bit'
      includeRootFolder: true
      archiveFile: '$(Build.ArtifactStagingDirectory)/amiberry-$(VERSION_TAG)-rpi3-sdl2-32bit.zip'
      
  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: $(Build.ArtifactStagingDirectory)
     ArtifactName: rpi3_sdl2_release